# Generated by Django 4.0.1 on 2022-01-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(choices=[('Accounting', 'Accounting'), ('Science', 'Science'), ('English', 'English'), ('Math', 'Math')], max_length=60),
        ),
    ]
